### ISSUE TITLE
hand_model.detect_image() error

### ISSUE THREAD

**Issue by weiguochow** [guohengkai/region-ensemble-network#13]
Hi,

Thank you for your nice code! I want to reproduce the results, Since the pyrs.start() doesn't work, then I am using pysr.service instead.  There is some following errors

Traceback (most recent call last):
  File "demo/show_cv2.py", line 75, in <module>
    results = hand_model.detect_image(d)
  File "/home/alex/PhD/PoseEstimation/REN/region-ensemble-network-master/evaluation/hand_model.py", line 42, in detect_image
    return self.detect_images([img])[0,...]
TypeError: 'NoneType' object has no attribute '__getitem__'

Can you give me some advice?

Regards,
weiguo

**Comment by xinghaochen** [comment]
Hi weiguo, 

Since you are using your own codes to predict hand pose from realsense camera, we can hardly figure out what the problems are without the complete codes. Here are some suggestions to make it works:
(1) Firstly you should make sure that your camera works properly by running the official [example demo](https://github.com/toinsson/pyrealsense/blob/master/examples/show_cv2.py) of  pyrealsense. 
(2) Based on the last issue, I suppose you are using pyrealsense 2.x. In that case, you might have a look at [this file](https://github.com/xinghaochen/region-ensemble-network/blob/master/demo/realsense_realtime_demo_new_pyrealsense.py). The current version of [realsense_realtime_demo.py](https://github.com/guohengkai/region-ensemble-network/blob/master/demo/realsense_realtime_demo.py) in this repository only supports pyrealsense 1.x. 
(3) If something still goes wrong, you can dig deep into [these lines](https://github.com/guohengkai/region-ensemble-network/blob/master/evaluation/hand_model.py#L25-L37) and print some debug messages to find out what exactly goes wrong.

Hope it helps.

**Comment by xinghaochen** [comment]
@weiguochow Hi, I'm sorry that the current codes have a bug that causes the error you mentioned.
You can add a line in the end of the function _transform_pose in [hand_model.py](https://github.com/guohengkai/region-ensemble-network/blob/3bc07818822e1a9d01fc9592461c05eaa47ed089/evaluation/hand_model.py#L107):
`return res_poses`
We will soon update the codes to fix bugs.

**Comment by weiguochow** [comment]
@xinghaochen 
Thank you very much for modifying the codes.
